const themes = {
  default: {
    '--primary-color': '#007bff',
    '--background-dark': '#343a40',
    '--background-light': '#f8f9fa',
    '--text-dark': '#212529',
    '--text-light': '#f8f9fa',
    '--border-color': '#ced4da',
    '--hover-color': '#0056b3',
    '--highlight': '#ffc107',
    '--header-height': '60px',
    '--overlay-bg': 'rgba(0, 0, 0, 0.5)',
    '--loading-bg': 'transparent',
    '--loader-border': '#f3f3f3',
    '--loader-border-top': '#3498db',
    '--loading-text-color': '#333',
    '--notification-bg': 'white',
    '--notification-box-shadow': 'rgba(0, 0, 0, 0.2)',
    '--notification-text-color': '#333',
    '--notification-button-bg': '#3498db',
    '--notification-button-hover-bg': '#2980b9',
    '--history-modal-bg': 'white',
    '--history-modal-box-shadow': 'rgba(0, 0, 0, 0.2)',
    '--history-modal-text-color': '#333',
    '--transaction-th-bg': '#e0e0e0',
    '--transaction-tr-even-bg': '#f5f5f5',
    '--transaction-tr-hover-bg': '#ddd',
    '--modal-button-bg': '#007bff',
    '--modal-button-hover-bg': '#0056b3',
    '--modal-overlay-bg': 'rgba(0, 0, 0, 0.7)',
    '--error-message-color': 'red',
    '--withdraw-modal-bg': 'white',
    '--withdraw-modal-box-shadow': 'rgba(0, 0, 0, 0.2)',
    '--withdraw-modal-text-color': 'black',
    '--balance-frame-border': '#007bff',
    '--balance-frame-bg': '#f9f9f9',
    '--balance-frame-box-shadow': 'rgba(0, 123, 255, 0.1)',
    '--balance-amount-color': '#007bff',
    '--input-border-color': '#ccc',
    '--input-focus-border-color': '#007bff',
  },
  tranquil: {
    '--primary-color': '#4a90e2',
    '--background-dark': '#2c3e50',
    '--background-light': '#ecf0f1',
    '--text-dark': '#34495e',
    '--text-light': '#ffffff',
    '--border-color': '#bdc3c7',
    '--hover-color': '#357ab7',
    '--highlight': '#e74c3c',
    '--header-height': '60px',
    '--overlay-bg': 'rgba(44, 62, 80, 0.5)',
    '--loading-bg': 'transparent',
    '--loader-border': '#d3d3d3',
    '--loader-border-top': '#4a90e2',
    '--loading-text-color': '#7f8c8d',
    '--notification-bg': '#ffffff',
    '--notification-box-shadow': 'rgba(0, 0, 0, 0.1)',
    '--notification-text-color': '#34495e',
    '--notification-button-bg': '#4a90e2',
    '--notification-button-hover-bg': '#357ab7',
    '--history-modal-bg': '#ffffff',
    '--history-modal-box-shadow': 'rgba(0, 0, 0, 0.1)',
    '--history-modal-text-color': '#34495e',
    '--transaction-th-bg': '#ecf0f1',
    '--transaction-tr-even-bg': '#fafafa',
    '--transaction-tr-hover-bg': '#e0e0e0',
    '--modal-button-bg': '#4a90e2',
    '--modal-button-hover-bg': '#357ab7',
    '--modal-overlay-bg': 'rgba(44, 62, 80, 0.7)',
    '--error-message-color': '#e74c3c',
    '--withdraw-modal-bg': '#ffffff',
    '--withdraw-modal-box-shadow': 'rgba(0, 0, 0, 0.1)',
    '--withdraw-modal-text-color': '#34495e',
    '--balance-frame-border': '#4a90e2',
    '--balance-frame-bg': '#ecf0f1',
    '--balance-frame-box-shadow': 'rgba(74, 144, 226, 0.1)',
    '--balance-amount-color': '#4a90e2',
    '--input-border-color': '#bdc3c7',
    '--input-focus-border-color': '#4a90e2',
  },
  autumn: {
    '--primary-color': '#d35400',
    '--background-dark': '#3c3c3c',
    '--background-light': '#f5f5f5',
    '--text-dark': '#2d2d2d',
    '--text-light': '#ffffff',
    '--border-color': '#dcdcdc',
    '--hover-color': '#a84300',
    '--highlight': '#e67e22',
    '--header-height': '60px',
    '--overlay-bg': 'rgba(44, 44, 44, 0.5)',
    '--loading-bg': 'transparent',
    '--loader-border': '#f3f3f3',
    '--loader-border-top': '#d35400',
    '--loading-text-color': '#666',
    '--notification-bg': '#ffffff',
    '--notification-box-shadow': 'rgba(0, 0, 0, 0.1)',
    '--notification-text-color': '#2d2d2d',
    '--notification-button-bg': '#d35400',
    '--notification-button-hover-bg': '#a84300',
    '--history-modal-bg': '#ffffff',
    '--history-modal-box-shadow': 'rgba(0, 0, 0, 0.1)',
    '--history-modal-text-color': '#2d2d2d',
    '--transaction-th-bg': '#f5f5f5',
    '--transaction-tr-even-bg': '#fafafa',
    '--transaction-tr-hover-bg': '#e0e0e0',
    '--modal-button-bg': '#d35400',
    '--modal-button-hover-bg': '#a84300',
    '--modal-overlay-bg': 'rgba(44, 44, 44, 0.7)',
    '--error-message-color': '#e74c3c',
    '--withdraw-modal-bg': '#ffffff',
    '--withdraw-modal-box-shadow': 'rgba(0, 0, 0, 0.1)',
    '--withdraw-modal-text-color': '#2d2d2d',
    '--balance-frame-border': '#d35400',
    '--balance-frame-bg': '#f5f5f5',
    '--balance-frame-box-shadow': 'rgba(211, 84, 0, 0.1)',
    '--balance-amount-color': '#d35400',
    '--input-border-color': '#dcdcdc',
    '--input-focus-border-color': '#d35400',
  },
  sunset: {
    '--primary-color': '#ff4500',
    '--background-dark': '#2b1e1e',
    '--background-light': '#ffe4e1',
    '--text-dark': '#4b2e2e',
    '--text-light': '#ffffff',
    '--border-color': '#d3a9a9',
    '--hover-color': '#cc3700',
    '--highlight': '#ff6347',
    '--header-height': '60px',
    '--overlay-bg': 'rgba(43, 30, 30, 0.5)',
    '--loading-bg': 'transparent',
    '--loader-border': '#f0d9d9',
    '--loader-border-top': '#ff4500',
    '--loading-text-color': '#6d4a4a',
    '--notification-bg': '#ffe4e1',
    '--notification-box-shadow': 'rgba(0, 0, 0, 0.1)',
    '--notification-text-color': '#4b2e2e',
    '--notification-button-bg': '#ff4500',
    '--notification-button-hover-bg': '#cc3700',
    '--history-modal-bg': '#ffe4e1',
    '--history-modal-box-shadow': 'rgba(0, 0, 0, 0.1)',
    '--history-modal-text-color': '#4b2e2e',
    '--transaction-th-bg': '#ffe4e1',
    '--transaction-tr-even-bg': '#faf3f3',
    '--transaction-tr-hover-bg': '#f0d9d9',
    '--modal-button-bg': '#ff4500',
    '--modal-button-hover-bg': '#cc3700',
    '--modal-overlay-bg': 'rgba(43, 30, 30, 0.7)',
    '--error-message-color': '#ff6347',
    '--withdraw-modal-bg': '#ffe4e1',
    '--withdraw-modal-box-shadow': 'rgba(0, 0, 0, 0.1)',
    '--withdraw-modal-text-color': '#4b2e2e',
    '--balance-frame-border': '#ff4500',
    '--balance-frame-bg': '#ffe4e1',
    '--balance-frame-box-shadow': 'rgba(255, 69, 0, 0.1)',
    '--balance-amount-color': '#ff4500',
    '--input-border-color': '#d3a9a9',
    '--input-focus-border-color': '#ff4500',
  },
  ocean: {
    '--primary-color': '#1e90ff',
    '--background-dark': '#2c3e50',
    '--background-light': '#dff9fb',
    '--text-dark': '#2e4053',
    '--text-light': '#ffffff',
    '--border-color': '#b2bec3',
    '--hover-color': '#1c75d8',
    '--highlight': '#00cec9',
    '--header-height': '60px',
    '--overlay-bg': 'rgba(44, 62, 80, 0.5)',
    '--loading-bg': 'transparent',
    '--loader-border': '#ecf0f1',
    '--loader-border-top': '#1e90ff',
    '--loading-text-color': '#2c3e50',
    '--notification-bg': '#dff9fb',
    '--notification-box-shadow': 'rgba(0, 0, 0, 0.1)',
    '--notification-text-color': '#2e4053',
    '--notification-button-bg': '#1e90ff',
    '--notification-button-hover-bg': '#1c75d8',
    '--history-modal-bg': '#dff9fb',
    '--history-modal-box-shadow': 'rgba(0, 0, 0, 0.1)',
    '--history-modal-text-color': '#2e4053',
    '--transaction-th-bg': '#dff9fb',
    '--transaction-tr-even-bg': '#f7faff',
    '--transaction-tr-hover-bg': '#ecf0f1',
    '--modal-button-bg': '#1e90ff',
    '--modal-button-hover-bg': '#1c75d8',
    '--modal-overlay-bg': 'rgba(44, 62, 80, 0.7)',
    '--error-message-color': '#00cec9',
    '--withdraw-modal-bg': '#dff9fb',
    '--withdraw-modal-box-shadow': 'rgba(0, 0, 0, 0.1)',
    '--withdraw-modal-text-color': '#2e4053',
    '--balance-frame-border': '#1e90ff',
    '--balance-frame-bg': '#dff9fb',
    '--balance-frame-box-shadow': 'rgba(30, 144, 255, 0.1)',
    '--balance-amount-color': '#1e90ff',
    '--input-border-color': '#b2bec3',
    '--input-focus-border-color': '#1e90ff',
  },
  black: {
    '--primary-color': '#0d0d0d',
    '--background-dark': '#000000',
    '--background-light': '#1a1a1a',
    '--text-dark': '#e0e0e0',
    '--text-light': '#f0f0f0',
    '--border-color': '#333333',
    '--hover-color': '#262626',
    '--highlight': '#4d4d4d',
    '--header-height': '60px',
    '--overlay-bg': 'rgba(0, 0, 0, 0.7)',
    '--loading-bg': 'transparent',
    '--loader-border': '#4d4d4d',
    '--loader-border-top': '#0d0d0d',
    '--loading-text-color': '#cccccc',
    '--notification-bg': '#1a1a1a',
    '--notification-box-shadow': 'rgba(0, 0, 0, 0.5)',
    '--notification-text-color': '#e0e0e0',
    '--notification-button-bg': '#0d0d0d',
    '--notification-button-hover-bg': '#262626',
    '--history-modal-bg': '#1a1a1a',
    '--history-modal-box-shadow': 'rgba(0, 0, 0, 0.5)',
    '--history-modal-text-color': '#e0e0e0',
    '--transaction-th-bg': '#333333',
    '--transaction-tr-even-bg': '#262626',
    '--transaction-tr-hover-bg': '#1a1a1a',
    '--modal-button-bg': '#0d0d0d',
    '--modal-button-hover-bg': '#262626',
    '--modal-overlay-bg': 'rgba(0, 0, 0, 0.7)',
    '--error-message-color': '#ff4c4c',
    '--withdraw-modal-bg': '#1a1a1a',
    '--withdraw-modal-box-shadow': 'rgba(0, 0, 0, 0.5)',
    '--withdraw-modal-text-color': '#e0e0e0',
    '--balance-frame-border': '#0d0d0d',
    '--balance-frame-bg': '#1a1a1a',
    '--balance-frame-box-shadow': 'rgba(13, 13, 13, 0.5)',
    '--balance-amount-color': '#e0e0e0',
    '--input-border-color': '#333333',
    '--input-focus-border-color': '#0d0d0d',
  }
};


export default themes;
